In [1]:
%pip install pyodbc  
%pip install python-dotenv

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pyodbc    
from dotenv import dotenv_values    #import the dotenv_values function from the dotenv package
import pandas as pd
import numpy as np
import plotly.graph_objs as go
 
import warnings
 
warnings.filterwarnings('ignore')

In [3]:
# Load environment variables from .env file into a dictionary
environment_variables = dotenv_values('.env')
 
# Get the values for the credentials you set in the '.env' file
server = environment_variables.get("server")
database = environment_variables.get("database")
username = environment_variables.get("username")
password = environment_variables.get("password")

In [4]:
# Create a connection string
connection_string = f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password};MARS_Connection=yes;MinProtocolVersion=TLSv1.2;"

In [6]:
# This will connect to the server and might take a few seconds to be complete.
 
connection = pyodbc.connect(connection_string)

In [7]:
# Now the sql query to get the data is what what you see below.
# Note that you will not have permissions to insert delete or update this database table.

In [8]:

# Now the sql query to get the data is what what you see below.
# Note that you will not have permissions to insert delete or update this database table.
 
query = '''SELECT * FROM dbo.LP1_startup_funding2020'''
query = '''SELECT * FROM dbo.LP1_startup_funding2021'''
data_2018 = pd.read_csv('C:\\Users\\TOBYCRIBS\\my vscode tuturial\\wayne\\startup_funding2018.csv')
data_2018
data_2019 = pd.read_csv('C:\\Users\\TOBYCRIBS\\my vscode tuturial\\wayne\\startup_funding2019.csv')
data_2019
data_2020 = pd.read_sql(query, connection)
data_2020
data_2021 = pd.read_sql(query, connection)
data_2021

Company_Brand  Founded HeadQuarter                 Sector  \
0     Unbox Robotics   2019.0   Bangalore             AI startup   
1             upGrad   2015.0      Mumbai                 EdTech   
2        Lead School   2012.0      Mumbai                 EdTech   
3            Bizongo   2015.0      Mumbai         B2B E-commerce   
4           FypMoney   2021.0    Gurugram                FinTech   
...              ...      ...         ...                    ...   
1204        Gigforce   2019.0    Gurugram  Staffing & Recruiting   
1205          Vahdam   2015.0   New Delhi       Food & Beverages   
1206    Leap Finance   2019.0   Bangalore     Financial Services   
1207    CollegeDekho   2015.0    Gurugram                 EdTech   
1208          WeRize   2019.0   Bangalore     Financial Services   

                                           What_it_does  \
0     Unbox Robotics builds on-demand AI-driven ware...   
1        UpGrad is an online higher education platform.   
2     LEAD School offers technology based school tra...   
3     Bizongo is a business-to-business online marke...   
4     FypMoney is Digital NEO Bank for Teenagers, em...   
...                                                 ...   
1204                  A gig/on-demand staffing company.   
1205  VAHDAM is among the world’s first vertically i...   
1206  International education loans for high potenti...   
1207  Collegedekho.com is Student’s Partner, Friend ...   
1208  India’s first socially distributed full stack ...   

                                               Founders  \
0                           Pramod Ghadge, Shahid Memon   
1     Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...   
2                            Smita Deorah, Sumeet Mehta   
3               Aniket Deb, Ankit Tomar, Sachin Agrawal   
4                                         Kapil Banwari   
...                                                 ...   
1204                        Chirag Mittal, Anirudh Syal   
1205                                         Bala Sarda   
1206                         Arnav Kumar, Vaibhav Singh   
1207                                       Ruchir Arora   
1208                      Vishal Chopra, Himanshu Gupta   

                                           Investor        Amount  \
0                       BEENEXT, Entrepreneur First    $1,200,000   
1          Unilazer Ventures, IIFL Asset Management  $120,000,000   
2                  GSV Ventures, Westbridge Capital   $30,000,000   
3                            CDC Group, IDG Capital   $51,000,000   
4     Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal    $2,000,000   
...                                             ...           ...   
1204                                Endiya Partners      $3000000   
1205                                       IIFL AMC     $20000000   
1206                                   Owl Ventures     $55000000   
1207               Winter Capital, ETS, Man Capital     $26000000   
1208                 3one4 Capital, Kalaari Capital      $8000000   

             Stage  
0     Pre-series A  
1             None  
2         Series D  
3         Series C  
4             Seed  
...            ...  
1204  Pre-series A  
1205      Series D  
1206      Series C  
1207      Series B  
1208      Series A  

[1209 rows x 9 columns]

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
#Rename columns of data_2018 to match combined_data
data_2018 = data_2018.rename(columns={
    'Company Name': 'Company_Brand',
    'Industry': 'Sector',
    'Round/Series': 'Stage',
    'Amount': 'Amount',
    'Location': 'HeadQuarter',
    'About Company': 'What_it_does'
})

In [12]:

# Add the 'Year' column
data_2018['Year'] = 2018
data_2019['Year'] = 2019
data_2020['Year'] = 2020
data_2021['Year'] = 2021

CONCATENATING

In [13]:
# Combine all datasets
df_combined = pd.concat([data_2019, data_2020, data_2021, data_2018], ignore_index=True)

In [14]:
# Convert the 'Year' column to datetime format (handling NaNs appropriately)
df_combined['Year'] = pd.to_datetime(df_combined['Year'], format='%Y', errors='coerce')

DATA CLEANING

In [16]:

# Check for duplicated columns
df_combined.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [17]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3033 entries, 0 to 3032
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Company/Brand  89 non-null     object        
 1   Founded        2476 non-null   float64       
 2   HeadQuarter    3012 non-null   object        
 3   Sector         3028 non-null   object        
 4   What it does   89 non-null     object        
 5   Founders       2496 non-null   object        
 6   Investor       2383 non-null   object        
 7   Amount($)      89 non-null     object        
 8   Stage          2131 non-null   object        
 9   Year           3033 non-null   datetime64[ns]
 10  Company_Brand  2944 non-null   object        
 11  What_it_does   2944 non-null   object        
 12  Amount         2938 non-null   object        
dtypes: datetime64[ns](1), float64(1), object(11)
memory usage: 308.2+ KB


AMOUNT COLUMN CLEANING

In [19]:

df_combined['Amount'].unique()

array([nan, '$1,200,000', '$120,000,000', '$30,000,000', '$51,000,000',
       '$2,000,000', '$188,000,000', '$200,000', 'Undisclosed',
       '$1,000,000', '$3,000,000', '$100,000', '$700,000', '$9,000,000',
       '$40,000,000', '$49,000,000', '$400,000', '$300,000',
       '$25,000,000', '$160,000,000', '$150,000', '$1,800,000',
       '$5,000,000', '$850,000', '$53,000,000', '$500,000', '$1,100,000',
       '$6,000,000', '$800,000', '$10,000,000', '$21,000,000',
       '$7,500,000', '$26,000,000', '$7,400,000', '$1,500,000',
       '$600,000', '$800,000,000', '$17,000,000', '$3,500,000',
       '$15,000,000', '$215,000,000', '$2,500,000', '$350,000,000',
       '$5,500,000', '$83,000,000', '$110,000,000', '$500,000,000',
       '$65,000,000', '$150,000,000,000', '$300,000,000', '$2,200,000',
       '$35,000,000', '$140,000,000', '$4,000,000', '$13,000,000', None,
       '$Undisclosed', '$2000000', '$800000', '$6000000', '$2500000',
       '$9500000', '$13000000', '$5000000', '$8000

In [20]:
# Function to clean and normalize the 'Amount' column
def clean_amount(amount):
    if pd.isna(amount) or amount in ['Undisclosed', '$Undisclosed', 'Upsparks']:
        return np.nan
    amount = amount.replace(',', '').replace('$', '').replace('₹', '')
    try:
        amount = float(amount)
    except ValueError:
        return np.nan
    return amount
 
# Apply the cleaning function to the 'Amount' column
df_combined['Amount'] = df_combined['Amount'].apply(clean_amount)
 
# Create a temporary column to identify the currency type
df_combined['Currency'] = df_combined['Amount'].apply(lambda x: 'INR' if '₹' in str(x) else 'USD')
 
# Function to convert all amounts to USD
def convert_currency(amount, currency):
    if currency == 'INR':
        return amount * 0.013  # Assuming an exchange rate of 1 INR = 0.013 USD
    return amount

In [21]:
# Convert all amounts to USD
df_combined['Amount'] = df_combined.apply(lambda row: convert_currency(row['Amount'], row['Currency']), axis=1)
 
# Drop the temporary 'Currency' column
df_combined.drop(columns=['Currency'], inplace=True)
 
# Convert the cleaned 'Amount' column to numeric, forcing errors to NaN
df_combined['Amount'] = pd.to_numeric(df_combined['Amount'], errors='coerce')
 
# Check for missing values before filling
missing_values_before = df_combined['Amount'].isnull().sum()
print(f"Missing values in 'Amount' column before filling: {missing_values_before}")
 
# Fill remaining missing values in 'Amount' column with the median value
df_combined['Amount'].fillna(df_combined['Amount'].median(), inplace=True)
 
# Check for missing values after filling
missing_values_after = df_combined['Amount'].isnull().sum()
print(f"Missing values in 'Amount' column after filling: {missing_values_after}")
 
# Check the cleaned DataFrame
df_combined.info()

Missing values in 'Amount' column before filling: 543
Missing values in 'Amount' column after filling: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3033 entries, 0 to 3032
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Company/Brand  89 non-null     object        
 1   Founded        2476 non-null   float64       
 2   HeadQuarter    3012 non-null   object        
 3   Sector         3028 non-null   object        
 4   What it does   89 non-null     object        
 5   Founders       2496 non-null   object        
 6   Investor       2383 non-null   object        
 7   Amount($)      89 non-null     object        
 8   Stage          2131 non-null   object        
 9   Year           3033 non-null   datetime64[ns]
 10  Company_Brand  2944 non-null   object        
 11  What_it_does   2944 non-null   object        
 12  Amount         3033 non-null   float64       
dtypes: datetime64[ns](

FOUNDED COLUMN CLEANING

In [22]:
df_combined['Founded'].unique()

array([  nan, 2014., 2004., 2013., 2010., 2018., 2019., 2017., 2011.,
       2015., 2016., 2012., 2008., 2021., 2020., 1993., 1999., 1989.,
       2009., 2002., 1994., 2006., 2000., 2007., 1978., 2003., 1998.,
       1991., 1984., 2005., 1963.])

In [23]:
# Handle missing values by filling with the forward fill
 
# Fill missing values with the forward fill
df_combined['Founded'] = df_combined['Founded'].fillna(method='ffill')
 
 
# If the first value is still NaT, use backward fill for the first value
df_combined['Founded'] = df_combined['Founded'].fillna(method='bfill')
 
# Check the DataFrame info to ensure proper conversion and filling
df_combined.info()
 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3033 entries, 0 to 3032
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Company/Brand  89 non-null     object        
 1   Founded        3033 non-null   float64       
 2   HeadQuarter    3012 non-null   object        
 3   Sector         3028 non-null   object        
 4   What it does   89 non-null     object        
 5   Founders       2496 non-null   object        
 6   Investor       2383 non-null   object        
 7   Amount($)      89 non-null     object        
 8   Stage          2131 non-null   object        
 9   Year           3033 non-null   datetime64[ns]
 10  Company_Brand  2944 non-null   object        
 11  What_it_does   2944 non-null   object        
 12  Amount         3033 non-null   float64       
dtypes: datetime64[ns](1), float64(2), object(10)
memory usage: 308.2+ KB


HEADQUARTER

In [24]:
df_combined['HeadQuarter'].unique()

array([nan, 'Mumbai', 'Chennai', 'Telangana', 'Pune', 'Bangalore',
       'Noida', 'Delhi', 'Ahmedabad', 'Gurugram', 'Haryana', 'Chandigarh',
       'Jaipur', 'New Delhi', 'Surat', 'Uttar pradesh', 'Hyderabad',
       'Rajasthan', 'Ahmadabad', None, 'Small Towns, Andhra Pradesh',
       'Goa', 'Rajsamand', 'Ranchi', 'Faridabad, Haryana', 'Gujarat',
       'Thane', 'Computer Games', 'Cochin', 'Gurgaon', 'Vadodara',
       'Food & Beverages', 'Pharmaceuticals\t#REF!', 'Gurugram\t#REF!',
       'Kolkata', 'Mohali', 'Indore', 'Powai', 'Ghaziabad', 'Nagpur',
       'West Bengal', 'Patna', 'Samsitpur', 'Lucknow', 'Silvassa',
       'Thiruvananthapuram', 'Faridabad', 'Roorkee', 'Ambernath',
       'Panchkula', 'Coimbatore', 'Andheri', 'Mangalore', 'Telugana',
       'Bhubaneswar', 'Kottayam', 'Beijing', 'Panaji', 'Satara',
       'Orissia', 'Jodhpur', 'New York', 'Santra', 'Mountain View, CA',
       'Trivandrum', 'Jharkhand', 'Kanpur', 'Bhilwara', 'Guwahati',
       'Online Media\t#REF!', 'K